using System;

namespace POE_Part3

{
    /// <summary>
    /// Represents a single cybersecurity-related task or reminder created by the
    /// user through the chatbot's task assistant feature. Each task is persisted
    /// to MySQL via the TaskService class.
    /// </summary>
    public class CyberTask
    {
        /// <summary>
        /// Primary key. Auto-generated by MySQL (AUTO_INCREMENT) — leave as 0 for
        /// new, unsaved tasks. TaskService.AddTask populates this after insertion.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Short title of the task, e.g. "Review privacy settings".
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Optional longer description giving more detail about the task.
        /// Can be null or empty if the user didn't provide one.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Optional reminder date for the task. Null if the user didn't set one.
        /// </summary>
        public DateTime? ReminderDate { get; set; }

        /// <summary>
        /// Whether the task has been marked complete.
        /// </summary>
        public bool IsCompleted { get; set; }

        /// <summary>
        /// When the task was created. Set automatically on construction.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        public CyberTask()
        {
            CreatedDate = DateTime.Now;
            IsCompleted = false;
        }

        public CyberTask(string title, string description, DateTime? reminderDate)
            : this()
        {
            Title = title;
            Description = description;
            ReminderDate = reminderDate;
        }

        /// <summary>
        /// Friendly, chat-style summary of the task, used when listing tasks
        /// back to the user in the chat window.
        /// </summary>
        public override string ToString()
        {
            string status = IsCompleted ? "✓ Done" : "◻ Pending";
            string reminder = ReminderDate.HasValue
                ? $" | Reminder: {ReminderDate.Value:dd MMM yyyy}"
                : "";
            string desc = string.IsNullOrWhiteSpace(Description)
                ? ""
                : $" — {Description}";

            return $"[{Id}] {status} | {Title}{desc}{reminder}";
        }
    }
}